intents:
  - intent: greeting
    examples: |
      - Здравствуйте
      - Привет!
      - привет
      - прив
      - привет бот
      - приветик
      - Доброе утро
      - Доброе утрецо
      - Добрый день
      - Добрый денек
      - Добрый вечер
      - Добрый вечерок
      - Рад вас видеть
      - Приветствую вас
      - приветствую
      - Здарово
      - Хай
      - Хеллоу
      - Здравствуйте

  - intent: goodbye
    examples: |
      - До свидания!
      - Пока!
      - Всего доброго!
      - Удачи!
      - До скорого!
      - Счастливо!
      - Без обид!
      - До встречи!
      - Всего хорошего!
      - Прощай!

  - intent: weather
    examples: |
      - Какая погода сегодня?
      - Какая будет погода завтра?
      - Какая погода на выходных?
      - Будет ли сегодня дождь?
      - Какой прогноз погоды на эту неделю?
      - Какой температуры ожидается сегодня?
      - Какая погода на улице сейчас?
      - Какой уровень влажности воздуха сегодня?
      - Какой скорости ветра ожидается сегодня?
      - Какое атмосферное давление сегодня?
      - погода
      - дождь
      - солнце

  - intent: kinopoisk
    examples: |
      - Что посмотреть в кино?
      - Какой фильм тебе нравится?
      - Какой фильм стоит посмотреть в выходной?
      - Какой фильм считается шедевром мирового кинематографа?
      - Посоветуй фильм
      - фильм
      - кино
      - посмотреть
      - глянуть кино
      - кинчик
      - посоветуй кинчик
      - киношка
      - сериал
      - какой сериал глянуть
      - посоветуй кино
      - посоветуй сериал

  - intent: citations
    examples: |
      - цитаты
      - цитата
      - цитатка
      - мысль
      - умная мысль
      - случайная цитата
      - цитата дня
      - мудрая мысль
      - скажи мысль
      - скажи цитату
      - покажи мысль
      - покажи цитату
      - высказываение
      - умное высказываение

  - intent: repeat
    examples: |
      - повторите
      - повтори
      - повтор
      - повтор давай
      - повтор пожалуйста
      - повтори пожалуйста
      - еще раз
      - еще раз пожалуйста
      - еще разок 
      - еще разок давай 
      - не понял
      - не услышал
      - продублируй
      - дальше
      - еще
      - не расслышал
      - межешь повторить
      - повтори еще раз
      - скажи еще раз
