intents:
  - intent: greeting
    examples: |
      - Здравствуйте!
      - Привет!
      - привет
      - Доброе утро!
      - Добрый день!
      - Добрый вечер!
      - Рад вас видеть!
      - Приветствую вас!
      - Здарово
      - Хай
      - Хеллоу
      - Здравствуйте

  - intent: goodbye
    examples: |
      - До свидания!
      - Пока!
      - Всего доброго!
      - Удачи!
      - До скорого!
      - Счастливо!
      - Без обид!
      - До встречи!
      - Всего хорошего!
      - Прощай!

  - intent: weather
    examples: |
      - Какая погода сегодня?
      - Какая будет погода завтра?
      - Какая погода на выходных?
      - Будет ли сегодня дождь?
      - Какой прогноз погоды на эту неделю?
      - Какой температуры ожидается сегодня?
      - Какая погода на улице сейчас?
      - Какой уровень влажности воздуха сегодня?
      - Какой скорости ветра ожидается сегодня?
      - Какое атмосферное давление сегодня?
      - погода
      - дождь
      - солнце

  - intent: kinopoisk
    examples: |
      - Что посмотреть в кино?
      - Какой фильм тебе нравится?
      - Какой фильм стоит посмотреть в выходной?
      - Какой фильм считается шедевром мирового кинематографа?
      - Посоветуй фильм
      - фильм
      - кино
      - посмотреть
      - глянуть кино
      - кинчик
      - киношка
      - сериал
      - какой сериал глянуть
      - посоветуй кино
      - посоветуй сериал
